version: '3.7'
services:
  web:
    build: .
    restart: always
    ports:
      - "50505:50505"
    links:
      - "mysql"
      - "redis"
    depends_on:
      - "mysql"
      - "redis"
  mysql:
    image: "mysql:5.6"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth1
      MYSQL_USER: auth1
      MYSQL_PASSWORD: password
  redis:
    image: "redis:5.0"
